### ISSUE TITLE
Error: 未知の引数です: config

### ISSUE THREAD

**Issue by narita1980** [dev-protocol/stakes.social#298]
# description
I get an error when I run a command.

```
% yarn build
yarn run v1.22.4
$ lerna run build --include-dependencies
lerna notice cli v3.22.1
lerna notice filter including dependencies
lerna info Executing command in 2 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in '@dev/graphql'
lerna ERR! yarn run build stdout:
$ yarn clean
$ rimraf esm cjs
$ graphql-codegen --config codegen.yml && run-p -l build:* && yarn format
Error: 未知の引数です: config
    at Array.<anonymous> (/Users/narita/github/stakes.social/node_modules/graphql-codegen/lib/cli.js:142:31)
    at Object.self.fail (/Users/narita/github/stakes.social/node_modules/yargs/lib/usage.js:35:17)
    at Object.self.unknownArguments (/Users/narita/github/stakes.social/node_modules/yargs/lib/validation.js:139:13)
    at parseArgs (/Users/narita/github/stakes.social/node_modules/yargs/yargs.js:811:32)
    at Object.get [as argv] (/Users/narita/github/stakes.social/node_modules/yargs/yargs.js:668:16)
    at Object.<anonymous> (/Users/narita/github/stakes.social/node_modules/graphql-codegen/lib/cli.js:143:19)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@dev/graphql'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
% 
```

**Comment by aggre** [comment]
@narita1980 Hi! Thank you for the report!

That bug did not reproduce in my environment.

And, codegen.yml is already here: https://github.com/dev-protocol/stakes.social/blob/master/packages/graphql/codegen.yml

What is using your yarn version?

**Comment by aggre** [comment]
@narita1980 Is this problem not solved yet?

**Comment by narita1980** [comment]
はい！これクローズで大丈夫です
ご回答ありがとうございました。
